name: RuboCop
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install RuboCop
      run: gem install rubocop
    - name: Run RuboCop
      run: bundle exec rubocop
