name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6
    - run:
      name: Install RuboCop
      command: gem install rubocop
    - run:
      name: Run RuboCop
      command: bundle exec rubocop
