name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install Dependencies
      run: bundle install
    - name: Run Tests
      run: bundle exec rake test
    strategy:
      matrix:
        ruby: [2.6, 2.5]
